### ISSUE TITLE
change filter

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/fewpjs-iterators-find-lab#6]
![Screen Shot 2020-02-19 at 8 46 34 PM](https://user-images.githubusercontent.com/18649892/74892902-ef957b80-5358-11ea-900a-fa6e79d8eef0.png)

I believe it should be: roommates.filter( s => s === "winston") 
![Screen Shot 2020-02-19 at 8 48 40 PM](https://user-images.githubusercontent.com/18649892/74893005-3edbac00-5359-11ea-8301-60869105a986.png)

**Comment by Sdcrouse** [comment]
@lizbur10 I believe this issue was fixed by one of my commits that you merged in a few weeks ago.

**Comment by lizbur10** [comment]
Thanks @Sdcrouse !

**Comment by Sdcrouse** [comment]
No problem!
